{{- range .Values.runners }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  namespace: github-runners
spec:
  replicas: {{ .replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
        - name: runner
          image: myoung34/github-runner:latest
          env:
            - name: REPO_URL
              value: "{{ .repoUrl }}"
            - name: RUNNER_NAME
              value: "{{ .name }}"
            - name: RUNNER_LABELS
              value: "{{ .labels }}"
            - name: ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-runner-secret
                  key: token
            - name: DOCKER_HOST
              value: "tcp://localhost:2375"
        - name: dind
          image: docker:20.10-dind
          securityContext:
            privileged: true
          args: ["--host=tcp://0.0.0.0:2375"]
          env:
            - name: DOCKER_TLS_CERTDIR
              value: ""
          volumeMounts:
            - name: dind-storage
              mountPath: /var/lib/docker
      volumes:
        - name: dind-storage
          emptyDir: {}
---
{{- end }}
